version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
    volumes:
      - ./backend/mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_nest
    restart: always
    ports:
      - "3407:3407"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user_crud
      - DB_PASSWORD=root
      - DB_NAME=db_crud
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    image: php:8.2-apache
    container_name: frontend_php
    restart: always
    ports:
      - "8087:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - backend
